vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        images:
            uri_prefix: '/images'
            upload_destination: '%images_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
