vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        logos:
            uri_prefix: '/images/logos'
            upload_destination: '%logos_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        images:
            uri_prefix: '/images/projects'
            upload_destination: '%images_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
